# Generated by Django 4.2.17 on 2024-12-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=60)),
                ('Apellidos', models.CharField(max_length=60)),
                ('Identificacion', models.CharField(max_length=10)),
                ('FechaNacimiento', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('RolName', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolOpciones',
            fields=[
                ('idOpcion', models.AutoField(primary_key=True, serialize=False)),
                ('NombreOpcion', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=120)),
                ('SessionActive', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('Status', models.CharField(choices=[('Activo', 'Se encuentra activo'), ('Inactivo', 'Se encuentra Inactivo'), ('Bloqueado', 'Se encuentra Bloqueado')], default='Activo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaIngreso', models.DateField()),
                ('FechaCierre', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rol')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.usuario')),
            ],
            options={
                'unique_together': {('Rol', 'Usuario')},
            },
        ),
        migrations.CreateModel(
            name='RolRolOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rol')),
                ('RolOpciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rolopciones')),
            ],
            options={
                'unique_together': {('Rol', 'RolOpciones')},
            },
        ),
    ]
