# Generated by Django 4.2.17 on 2024-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rolopciones_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='FechaCierre',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='FechaIngreso',
            field=models.DateTimeField(),
        ),
    ]
